<a href="https://colab.research.google.com/github/redman157/HocML/blob/master/K-means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
K = 3
X = np.random.rand(41,2)
c = np.random.rand(1,K)
n = X.shape[0]
def euclidian(a,b):
  return np.linalg.norm(a,b)
# plt.figure(figsize = (8,8))
# plt.scatter(x = X,y = c, markers = ('x','o'))
# plt.xlabels('Labels_X')
# plt.ylabels('Labels_y')
# plt.show()
history_centroids = []
def k_means(K,epsilon = 0,distance = 'euclidian'):
  if distance == 'euclidian':
    dis_method = euclidian
# set up gia tri row = num_instances va col = num_features
  num_instances, num_features = X.shape
# lay gia tri t
  prototypes = X[np.random.randint(0, num_instances - 1, size = K)]
# add no vao giai doan hoi tu
  history_centroids.append(prototypes)
# khi update prototypes moi thi can xoa bo nho cua prototypes cu
  prototypes_old = np.zeros(prototypes.shape)
# luu tru clusters
  belongs_to = np.zeros((num_instances,1))
  norm = dist_method(prototypes, prototypes_old)
  iteration = 0
  while norm > epsilon:
    iteration += 1
    norm = dist_method(prototypes,prototypes_old)
    # voi moi dong cua instances trong X
    for index_instances, instances in enumerate(X):
      # xac dinh khoang cach vector toi K

In [0]:
import numpy as np

def kMeans(X, K, maxIters = 10, plot_progress = None):

    centroids = X[np.random.choice(np.arange(len(X)), K), :]
    for i in range(maxIters):
        # Cluster Assignment step
        C = np.array([np.argmin([np.dot(x_i-y_k, x_i-y_k) for y_k in centroids]) for x_i in X])
        # Move centroids step
        centroids = [X[C == k].mean(axis = 0) for k in range(K)]
        if plot_progress != None: plot_progress(X, C, np.array(centroids))
    return np.array(centroids) , C

In [0]:
X = np.random.rand(40,2)
K = 3
kMeans(X,K)

(array([[0.77536086, 0.11534011],
        [0.70360512, 0.58273258],
        [0.23291576, 0.58476612]]),
 array([2, 2, 1, 2, 0, 1, 1, 0, 0, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 0, 0, 2,
        1, 0, 1, 2, 1, 2, 1, 1, 2, 2, 0, 1, 0, 0, 0, 1, 2, 2]))

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import random
from random import randint
def k_means(X, K):
  # tao ra ma tran voi 4 diem K tuong ung nam trong X
  rand_K = np.random.choice(len(X),K)
  centroids = X[rand_K,:]
  for i in range(10):
    C = []
    for x_i in X:
      dot = []
      for y_k in centroids:
        dot.append(np.dot(x_i-y_k, x_i-y_k))
      C.append(np.argmin(dot))
    C = np.array(C)
    for k in range(K):
      centroids.append[X[C == K].mean(axis = 0)]
    if plot_progress != None: plot_progress(X, C, np.array(centroids))
  return np.array(centroids) , C

In [0]:
X = np.random.rand(40,2)
K = 3
k_means(X,K)

In [0]:
X = np.random.rand(40,2)
K = 3
kMeans(X,K)

(array([[0.71739723, 0.62754881],
        [0.20655343, 0.78184577],
        [0.242293  , 0.21288915]]),
 array([2, 0, 2, 2, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 2, 2, 0, 0, 0,
        2, 0, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 0, 1, 2, 0, 2, 2]))

In [3]:
import numpy as np
import os
def euclidean(point, centroids):
  return np.sqrt(np.sum((point, centroids) ** 2))

def assign_label_cluster(distance,data_point, centroids):
  #gan nhan cho cac label phan cum
  index_of_minimum = min(distance, key=distance.get)
  return [index_of_minimum, data_point, centroids[index_of_minimum]]

def computed_new_centroids(cluster_label, centroids):
  return np.array(cluster_label + centroids) / 2

def iterate_k_means(data_points, centroids, total_iteration):
  label = []
  cluster_label = []
  total_points = len(data_points)
  k = len(centroids)
  for interation in range(0, total_iteration):
    # chay vòng lap tat cả các lan lap
    for index_point in range(0, total_points):
      # chay tat ca cac diem
      distance = {}
      for index_centroids in range(0, k):
        distance[index_centroids] = computed_new_centroids(data_points[index_point], centroids[index_points])
        # tinh khoang cach tu data den centroids
      label = assign_label_cluster(distance, data_point[index_point],centroids)
      centroids[label[0]] = compute_new_centroids(label[1], centroids[label[0]])
      
      if iteration == (total_iteration - 1 ):
        cluster_label.append(label)
  return [cluster_label, centroids]

def print_label_data(result):
    print("Result of k-Means Clustering: \n")
    for data in result[0]:
        print("data point: {}".format(data[1]))
        print("cluster number: {} \n".format(data[0]))
    print("Last centroids position: \n {}".format(result[1]))

def create_centroids():
    centroids = []
    centroids.append([5.0, 0.0])
    centroids.append([45.0, 70.0])
    centroids.append([50.0, 90.0])
    return np.array(centroids)

if __name__ == "__main__":
    filename = os.path.dirname(__file__) + "\data.csv"
    data_points = np.genfromtxt(filename, delimiter=",")
    centroids = create_centroids()
    total_iteration = 100
    
    [cluster_label, new_centroids] = iterate_k_means(data_points, centroids, total_iteration)
    print_label_data([cluster_label, new_centroids])
    print()
        

NameError: ignored

In [1]:
a = {}
print(type(a))

<class 'dict'>
