<a href="https://colab.research.google.com/github/redman157/HocML/blob/master/recommander-basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!pip install lightfm

In [41]:
import numpy as np
import scipy
from lightfm.datasets import fetch_movielens
from lightfm import LightFM
data = fetch_movielens(min_rating = 4.0)
model = LightFM(loss = 'warp')
model.fit(data['train'],
          epochs=30,
          num_threads = 2)
def sample_recommendation(model,data,user_ids):
  # lay so luong toan bo data
  n_users, n_items = data['train'].shape
  
  for user_id in user_ids:
    # tao ra recommendation cho moi user tham gia
    known_positives = data['item_labels'][data['train'].tocsr()[user_id].indices]
    # tra ve gia tri predict tuong ung voi so luong thich cua moi movie
    scores = model.predict(user_id, np.arange(n_items))
    # muc do danh gia xep hang thong qua luong thich
    top_items = data['item_labels'][np.argsort(-scores)]
    print("User %s" % user_id)
    print("     Known positives:")

    for x in known_positives[:3]:
      print("        %s" % x)
      print("     Recommended:")
    for x in top_items[:3]:
      print("        %s" % x)

sample_recommendation(model, data, [3, 25, 450])

User 3
     Known positives:
        Seven (Se7en) (1995)
     Recommended:
        Contact (1997)
     Recommended:
        Starship Troopers (1997)
     Recommended:
        Cop Land (1997)
        Scream (1996)
        Chasing Amy (1997)
User 25
     Known positives:
        Dead Man Walking (1995)
     Recommended:
        Star Wars (1977)
     Recommended:
        Fargo (1996)
     Recommended:
        English Patient, The (1996)
        Contact (1997)
        Fargo (1996)
User 450
     Known positives:
        Contact (1997)
     Recommended:
        George of the Jungle (1997)
     Recommended:
        Event Horizon (1997)
     Recommended:
        Kiss the Girls (1997)
        I Know What You Did Last Summer (1997)
        Scream (1996)


In [40]:
data['train']

IndexError: ignored

In [0]:
from numpy import array
from scipy.sparse import coo_matrix
row  = array([0,0,1,3,1,0,0])
col  = array([0,2,1,3,1,0,0])
data = array([1,1,1,1,1,1,1])
A = coo_matrix( (data,(row,col)), shape=(5,5)).tocsr()
#known_positives = data['item_labels'][data['train'].tocsr()[user_id].indices]
 

In [34]:
print(row)
print(col)
print(data)
print(A)

[0 0 1 3 1 0 0]
[0 2 1 3 1 0 0]
[1 1 1 1 1 1 1]
  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
  (3, 3)	1


In [44]:
data['item_labels']


array(['Toy Story (1995)', 'GoldenEye (1995)', 'Four Rooms (1995)', ...,
       'Sliding Doors (1998)', 'You So Crazy (1994)',
       'Scream of Stone (Schrei aus Stein) (1991)'], dtype=object)

In [45]:
data['train']

<943x1682 sparse matrix of type '<class 'numpy.float32'>'
	with 49906 stored elements in COOrdinate format>